version: "3.8"

services:
  db:
    container_name: memorialisation-db
    environment:
      MYSQL_USER: vivedia
      MYSQL_DATABASE: memorialisation
      MYSQL_ROOT_PASSWORD: "MySQLRootPassword"
      MYSQL_PASSWORD: "MySQLUserPassword"
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  testdb:
    container_name: memorialisation-testdb
    environment:
      MYSQL_USER: vivedia
      MYSQL_DATABASE: memorialisation
      MYSQL_ROOT_PASSWORD: "MySQLRootPassword"
      MYSQL_PASSWORD: "MySQLUserPassword"
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"

  phpmyadmin:
    container_name: memorialisation-phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: memorialisation-db
      MYSQL_ROOT_PASSWORD: "MySQLRootPassword"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 5s
    image: phpmyadmin
    ports:
      - "5050:80"

  web:
    build:
      context: .
      args:
        - "APP_ENV=${APP_ENV:-local}"
        - "NODE_ENV=${NODE_ENV:-local}"
        - "MAIL_MAILER=log"
        - "NR_KEY=${NR_KEY}"
        - "NR_APP_REF=${NR_APP_REF}"
    image: web-image
    container_name: "memorialisation-web"
    volumes:
      - .:/var/www/html/
      - /var/www/html/vendor/
    ports:
      - 8080:8080

  webpack:
    image: web-image
    container_name: "memorialisation-webpack"
    command: ["./run-webpack.sh"]
    volumes:
      - ./resources:/var/www/html/resources
      - ./public:/var/www/html/public

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - EXTRA_CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:8080,http://admin.localhost:8080
    networks:
      default:
        aliases:
          - s3.localhost.localstack.cloud
          - s3-website.localhost.localstack.cloud
          - vivedia-bucket.s3.localhost.localstack.cloud
          - vivedia-bucket.s3-website.localhost.localstack.cloud
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./aws:/docker-entrypoint-initaws.d"

volumes:
  db_data:
